t=0:pi/15:5*pi;
figure
[X,Y,Z]=cylinder(2*sin(t));
surf(X,Y,Z,'LineWidth',1)
title('Cylinder')

GO_p=uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.05 0.1 0.1 0.08],...
 'backgroundcolor',[0 0 0],...
 'foregroundcolor',[1 1 1],...
 'String','CLOSE',...
 'Callback','close');