function interfata2(A,f)
t=0:0.001:0.004;
vin=A*sin(2*pi*f*t);
vout = zeros(size(vin));
for i = 1:length(t)
    if(vin(i) >=0)
        vout(i)=vin(i);
    end 
end
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.91 0.84 0.08 .05],...
    'Backgroundcolor',[ 1 1 0.9],...
    'String','A');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.80 0.08 .05],...
    'String','A',...
    'Callback',['A=','str2num(get(gco,''String''));interfata2(A,f);']);
uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.91 0.64 0.08 .05],...
'Backgroundcolor',[1 1 0.9],...
    'String','f');
uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.60 0.08 .05],...
    'String','f',...
    'Callback',['f=','str2num(get(gco,''String''));interfata2(A,f);']);
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.91 0.2 0.08 .05],...
    'String','Reset to Initial Values',...
    'FontName','Arial',...
    'Callback','interfata2(1,50);');
plot(t,vout)
xlabel('time_{Sec}')
ylabel({'Amplitude'})
end