function interfata(A,f)
t=0:1e-3:50e-3;
v=A*cos(2*pi*f*t);
a_rad = (60*pi/180);
i=10*cos(2*pi*f*t + a_rad);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.91 0.84 0.08 .05],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'String','A');
 uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.80 0.08 .05],...
    'String','A',...
    'Callback',['A=','str2num(get(gco,''String''));interfata(A,f);']);

 uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.91 0.64 0.08 .05],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'String','f');

 uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.91 0.60 0.08 .05],...
    'String','f',...
    'Callback',['f=','str2num(get(gco,''String''));interfata(A,f);']);

 uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.91 0.2 0.08 .05],...
    'String','Reset to Initial Values',...
    'FontName','Arial',...
    'Callback','interfata(10,50);');

 plot(t,v,t,i,'o','Linewidth',2)
title('Voltage and current')
xlabel('time_{Sec}')
ylabel({'Voltage_{V}','Current_{mA}'})
text(0.045,0, 'v(t)','FontSize', 12);
text(0.012,6, 'i(t)','FontSize', 12);

end
