
Figc3=figure('Name','RC voltage',...
    'Units','normalized',...
    'NumberTitle','off',...
    'Position',[0.1 0.1 0.5 0.5],...
    'Color',[1 1 1]);

t = 0:0.5:4;
v= 6*exp(-2*t);
plot(t,v,'Linewidth',2)
title('RC voltage', 'FontSize', 14,'Color','r')
xlabel('time t_{sec}','FontSize',10)
ylabel('Voltage Voltage_{Volts}','FontSize',10)

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.91 0.93 0.08 .05],...
    'string','CLOSE',...
    'backgroundcolor',[0 0 0],...
    'FontName','Arial',...
    'foregroundcolor',[1 1 1],...
    'FontWeight','bold',...
    'FontSize',12,...
    'Callback','close');

h = uimenu('Label','Rc image','Callback','figa');






