Fig_t=figure('Name','TRIGONOMETRIC FUNCTIONS',... 
'Units','normalized',... 
'Position',[.1 .1 .5 .5],...
'NumberTitle','off','color',[0 0.5 1]); 

GO_p=uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.05 0.1 0.1 0.08],...
 'backgroundcolor',[1 0 1],...
 'foregroundcolor',[1 1 1],...
 'String','CLOSE',...
 'Callback','close');

GO_t=uicontrol('Style','text',...
 'Units','normalized',...
'Position',[0.3 0.8 0.2 0.13],...
'backgroundcolor',[1 0.5 1],...
'foregroundcolor',[1 1 1],...
'FontSize',20,...
'String','Trigonometric functions');

ha = axes('units','normalized',...
    'Position',[0 0 1 1]);
uistack(ha,'bottom');
I=imread('Trig.png');
hi = imagesc(I);
colormap gray;

GO_rb1=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.55 0.80 0.3 0.08],...
 'backgroundcolor',[1 0 1],...
 'foregroundcolor',[1 1 1],...
 'FontSize',14,...
 'String','Difference (sin,cos,tan)',...
 'Callback','main1_trig');

GO_rb2=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.22 0.48 0.15 0.08],...
 'backgroundcolor',[1 0 1],...
 'foregroundcolor',[1 1 1],...
 'FontSize',16,...
 'String','Animation',...
 'Callback','animation');

GO_rb3=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.35 0.24 0.25 0.08],...
 'backgroundcolor',[1 0 1],...
 'foregroundcolor',[1 1 1],...
 'FontSize',16,...
 'String','Cos/Sin overlay',...
 'Callback','main2_trig');














