A=10;
B=5;
C=1;
D=5;
f=50; 
N=4;

Fig=figure('Name','Difference(sin,cos,tan)',...
    'Units','normalized',...
    'NumberTitle','off',...
    'Position',[0.1 0.1 0.8 0.8],...
    'Color',[1 0.5 0.5]);

uicontrol('Style','text',...
'Units','normalized',...
    'Position',[0.55 0.95 0.3 .03],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',14,...
    'String','Default values: A=10, B=5, C=1, D=5, f=50, N=4');

trig(A,B,f,N,C,D);


