
A=10;
f=50; 
figc=figure('Name','voltage and current RL',...
    'Units','normalized',...
    'NumberTitle','off',...
    'Position',[0.1 0.1 0.5 0.5],...
    'Color',[0. 0.5 1]);

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.91 0.93 0.08 .05],...
    'string','CLOSE',...
    'backgroundcolor',[0 0 1],...
    'FontName','Arial',...
    'foregroundcolor',[1 1 1],...
    'FontWeight','bold',...
    'FontSize',12,...
    'Callback','close');

uicontrol('Style','text',...
'Units','normalized',...
    'Position',[0.1 0.94 0.3 .05],...
    'Backgroundcolor',[0 0 1],...
    'FontName','Arial',...
    'foregroundcolor',[1 1 1],...
    'FontSize',12,...
    'String','Default values: A=10,f=50,');

interfata(A,f);

h = uimenu('Label','RL image','Callback','figb');
