A=1;
f=50; 
figc2=figure('Name','output voltage DR',...
    'Units','normalized',...
    'NumberTitle','off',...
    'Position',[0.1 0.1 0.5 0.5],...
    'Color',[1 1 0]);

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.91 0.93 0.08 .05],...
    'string','CLOSE',...
    'backgroundcolor',[1 1 0],...
    'FontName','Arial',...
    'foregroundcolor',[0 0 0],...
    'FontWeight','bold',...
    'FontSize',12,...
    'Callback','close');

uicontrol('Style','text',...
'Units','normalized',...
    'Position',[0.1 0.94 0.3 .05],...
    'Backgroundcolor',[1 1 0.5],...
    'FontName','Arial',...
    'foregroundcolor',[0 0 0],...
    'FontSize',12,...
    'String','Default values: A=1,f=50,');
interfata2(A,f);

h = uimenu('Label','DR image','Callback','figc1');
