Fig_3=figure('Name','3D PLOTS',... 
'Units','normalized',... 
'Position',[.1 .1 .5 .5],...
'NumberTitle','off'); 

GO_p=uicontrol('Style','pushbutton',...
 'Units','normalized',...
 'Position',[0.05 0.1 0.1 0.08],...
 'backgroundcolor',[1 1 0],...
 'foregroundcolor',[0 0 0],...
 'String','CLOSE',...
 'Callback','close');


ha = axes('units','normalized',...
    'Position',[0 0 1 1]);
uistack(ha,'bottom');
I=imread('3D.png');
hi = imagesc(I);
colormap gray;

GO_rb1=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.55 0.80 0.2 0.08],...
 'backgroundcolor',[1 1 0],...
 'foregroundcolor',[0 0 0],...
 'FontSize',18,...
 'String','MESHGRID',...
 'Callback','meshs');

GO_rb2=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.22 0.48 0.3 0.08],...
 'backgroundcolor',[1 1 0],...
 'foregroundcolor',[0 0 0],...
 'FontSize',16,...
 'String','CYLINDER',...
 'Callback','cylinder1');

GO_rb3=uicontrol('Style','radiobutton',...
 'Units','normalized',...
 'Position',[0.35 0.24 0.28 0.08],...
 'backgroundcolor',[1 1 0],...
 'foregroundcolor',[0 0 0],...
 'FontSize',18,...
 'String','SIMPLE 3D PLOT',...
 'Callback','d3plot');