function trig(A,B,f,N,C,D)
T=1/f; 
t=0:T/100:N*T; 
x1=A*sin(2*pi*f*t); 
x2=B*cos(10*2*pi*f*t); 
x3=x1-x2;
x4=C*tan(2*pi*f*t);
x5=D*tan(5*2*pi*f*t);
x6=x4-x5;


    
uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.9 0.9 0.08 .05],...
    'string','CLOSE',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',12,...
    'Callback','close');

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.83 0.08 .05],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'String','A');

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.80 0.08 .05],...
    'String','A',...
    'Callback',['A=','str2num(get(gco,''String''));trig(A,B,f,N,C,D);']);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.63 0.08 .05],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'String','C');

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.60 0.08 .05],...
'String','C',...
    'Callback',['C=','str2num(get(gco,''String''));trig(A,B,f,N,C,D);']);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.53 0.08 .05],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'String','D');

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.50 0.08 .05],...
    'String','D',...
    'Callback',['D=','str2num(get(gco,''String''));trig(A,B,f,N,C,D);']);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.73 0.08 .05],...
    'backgroundcolor',[0.5 0.5 0.9],...
    'string','B');

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.70 0.08 .05],...
    'String','B',...
    'Callback',['B=','str2num(get(gco,''String''));trig(A,B,f,N,C,D)']);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.33 0.08 .05],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'String','f');

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.30 0.08 .05],...
    'String','f',...
    'Callback',['f=','str2num(get(gco,''String''));trig(A,B,f,N,C,D)']);

uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.9 0.43 0.08 .05],...
    'Backgroundcolor',[0.5 0.5 0.9],...
    'String','N');

uicontrol('Style','edit',...
    'Units','normalized',...
    'Position',[0.9 0.40 0.08 .05],...
    'String','N',...
    'Callback',['N=','str2num(get(gco,''String''));trig(A,B,f,N,C,D)']);

uicontrol('Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.9 0.2 0.08 .05],...
    'String','Reset to Initial Values',...
    'FontName','Arial',...
    'Callback','trig(10,5,50,4,10,5);');

subplot('position',[0.07 0.72 0.3 0.20]);
plot(t,x1);
grid on;
title('Sinus ');
xlabel('time [s]');
ylabel('Amplitude [V]');

subplot('position',[0.07 0.38 0.3 0.20]);
plot(t,x2);
grid on;
title('Cosinus ');
xlabel('time [s]');
ylabel('Amplitude [V]');

subplot('position',[0.07 0.05 0.3 0.20]);
plot(t,x3);
grid on;
title('Difference 1 ');
xlabel('time [s]');
ylabel('Amplitude [V]');

subplot('position',[0.5 0.72 0.3 0.20]);
plot(t,x4);
grid on;
title('Tangent 1 ');
xlabel('time [s]');
ylabel('Amplitude [V]');

subplot('position',[0.5 0.38 0.3 0.20]);
plot(t,x5);
grid on;
title('Tangent2 ');
xlabel('time [s]');
ylabel('Amplitude [V]');

subplot('position',[0.5 0.05 0.3 0.20]);
plot(t,x6);
grid on;
title('Difference 2 ');
xlabel('time [s]');
ylabel('Amplitude [V]');

end





